apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "https://localhost:8080"


 # Servicio de notificaciones en teams
  service.teams: |
    recipientUrls:
      GitOps: $teams-webhook-url

  # Trigger para OutOfSync
  trigger.on-outofsync: |
    - when: app.status.sync.status == 'OutOfSync'
      send: [app-outofsync-teams]

  # Trigger para vuelta a sincronización
  trigger.on-sync-succeeded: |
    - when: app.status.sync.status == 'Synced'
      send: [app-sync-succeeded]

  template.app-sync-succeeded: |
    teams:
      themeColor: "#00a000"
      sections: |
        [{
          "facts": [
            {
              "name": "Estado de sincronización: ",
              "value": "{{.app.status.sync.status}}"
            },
            {
              "name": "Repositorio: ",
              "value": "{{.app.spec.source.repoURL}}"
            }
          ]
        }]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
          }]
        }]
      title: La aplicacion "{{.app.metadata.name}}" ha sido sincronizada exitosamente!
      text: Aplicación {{.app.metadata.name}} sincronizada a las {{.app.status.operationState.finishedAt}} horas.
      summary: "{{.app.metadata.name}} exitosamente sincronizada"

  # Template para alertas de desincronización
  template.app-outofsync-teams: |
    teams:
      themeColor: "#ff0000"
      sections: |
        [{
          "facts": [
            {
              "name": "Estado de sincronización: ",
              "value": "{{.app.status.sync.status}}"
            },
            {
              "name": "Repositorio: ",
              "value": "{{.app.spec.source.repoURL}}"
            }
          ]
        }]
      potentialAction: |-
        [{
          "@type":"OpenUri",
          "name":"Operation Details",
          "targets":[{
            "os":"default",
            "uri":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
          }]
        }]
      title: La aplicación "{{.app.metadata.name}}" ha perdido el estado de sincronización!
      text: Aplicación {{.app.metadata.name}} dessincronizada a las {{.app.status.operationState.finishedAt}} horas.
      summary: "{{.app.metadata.name}} desincronizada!"


  