apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: "https://localhost:8080"


 # Servicio Teams
  service.teams: |
    webhook: $teams-webhook-url
    recipientUrls:
      channelName: $teams-webhook-url

  # Trigger para OutOfSync
  trigger.on-outofsync: |
    - when: app.status.sync.status == 'OutOfSync'
      send: [app-outofsync-teams]

  # Template para alertas
  template.app-outofsync-teams: |
    teams:
      message: |
        {
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "themeColor": "FF0000",
          "summary": "ArgoCD Alert",
          "sections": [{
            "activityTitle": "🚨 Aplicación {{.app.metadata.name}} con problemas",
            "facts": [
              { "name": "Estado de Salud", "value": "{{.app.status.health.status}}" },
              { "name": "Estado de Sync", "value": "{{.app.status.sync.status}}" },
              { "name": "Proyecto", "value": "{{.app.spec.project}}" },
              { "name": "Namespace", "value": "{{.app.spec.destination.namespace}}" },
              { "name": "Última sincronización", "value": "{{.app.status.operationState.finishedAt}}" }
            ],
            "markdown": true
          }],
          "potentialAction": [{
            "@type": "OpenUri",
            "name": "Abrir en ArgoCD",
            "targets": [
              { "os": "default", "uri": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}" }
            ]
          }]
        }

  