apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
stringData:
  teams-webhook-url: "https://bancoestado.webhook.office.com/webhookb2/b3ad9657-8d6e-4000-b5c7-fce4643ba956@189d9de0-0fef-4050-9094-e7cf9e6b3bb5/IncomingWebhook/08bb057e678e4e9788e58eecd4b86e1a/9ae1ded1-6bc8-446e-8e7e-272734533242/V2yb1qI1KFUVOxUq62bshISuC_j4UqGssUaY_oypdntG41"

