apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ms-rust
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-ms-rust
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-ms-rust
    spec:
      containers:
      - image: 279527989600.dkr.ecr.us-east-1.amazonaws.com/mitotech:ms-rust.latest
        imagePullPolicy: Always
        name: test-ms-rust
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
# --- Service Definition for test-ms-rust ---
# This Service exposes your Deployment within the cluster
# so that the Ingress can route traffic to it.

apiVersion: v1
kind: Service
metadata:
  name: test-ms-rust-svc  # Name of the Service
  namespace: test          # Namespace where your Deployment is
  labels:
    app: test-ms-rust      # Label to associate with the Ingress or for other selectors
spec:
  selector:
    app: test-ms-rust  # This MUST match the 'matchLabels.app' in your Deployment
  ports:
    - name: http         # Optional: A name for the port
      protocol: TCP
      port: 3000       # Port on which the Service will be exposed
      targetPort: 3000   # Port your container (test-ms-rust) is listening on
  type: ClusterIP        # Use ClusterIP when alb.ingress.kubernetes.io/target-type: ip
                         # Use NodePort if alb.ingress.kubernetes.io/target-type: instance

---
# --- Ingress Definition for test-ms-rust using ALB ---
# This Ingress resource will instruct the AWS Load Balancer Controller
# to provision an Application Load Balancer for your service.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ms-rust-ingress
  namespace: test # Namespace where your Deployment and Service are
  annotations:
    # --- AWS Load Balancer Controller Specific Annotations ---

    # Scheme: 'internet-facing' for public ALBs, 'internal' for private ALBs.
    alb.ingress.kubernetes.io/scheme: internal

    # Target Type: 'ip' to route traffic directly to Pod IPs (recommended for EKS).
    # 'instance' routes to NodePort on EC2 instances.
    alb.ingress.kubernetes.io/target-type: ip

    # Listener Ports: Defines the ports the ALB will listen on.
    # Default is HTTP:80 if not specified and no TLS.
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    # For HTTPS, you would add: '[{"HTTP": 80}, {"HTTPS": 443}]'
    # and configure alb.ingress.kubernetes.io/certificate-arn.

    
    # Health Check Path: Customize the health check path for the target group.
    # Your application should return a 200 OK on this path.
    # alb.ingress.kubernetes.io/healthcheck-path: /health # Replace with your app's health check endpoint
    # alb.ingress.kubernetes.io/healthcheck-port: 'traffic-port' # Or a specific port
    # alb.ingress.kubernetes.io/healthcheck-protocol: HTTP

    
    # Other useful annotations:
    alb.ingress.kubernetes.io/tags: tipo=privado
    
spec:
  # This field is crucial for specifying the Ingress controller.
  # It should match the controller you have deployed (AWS Load Balancer Controller).
  ingressClassName: alb
  rules:
    # You should replace 'your-eks-cluster-domain.com' with your actual domain
    # or remove the 'host' field if you are testing with the ALB's DNS name directly.
    # If 'host' is not specified, the rule applies to all virtual hosts.
    - host: 
      http:
        paths:
          - path: / # The path you want to expose your service on.
            pathType: Prefix # Options: Prefix, Exact, ImplementationSpecific
            backend:
              service:
                name: test-ms-rust-svc # Must match the Service name defined above
                port:
                  number: 3000 # Must match the 'port' defined in the Service
